// Cấu hình nội dung — chỉnh sửa tại đây là toàn bộ trang đổi theo.
window.heartConfig = {
  messages: [
    "Anh yêu em",
    "Cô gái bé nhỏ của anh",
    "Có em, ngày nào cũng đẹp",
    "Bình yên của anh là em",
    "Cảm ơn em đã đến",
    "Yêu em, hôm nay và mãi sau ❤",
  ],
  images: [
    "./images/photos/photo-1.jpg",
    "./images/photos/photo-2.jpg",
    "./images/photos/photo-3.jpg",
    "./images/photos/photo-4.jpg",
    "./images/photos/photo-5.jpg",
    "./images/photos/photo-6.jpg",
    "./images/photos/photo-7.jpg",
    "./images/photos/photo-8.jpg",
    "./images/photos/photo-9.jpg",
    "./images/photos/photo-10.jpg",
    "./images/photos/photo-11.jpg",
    "./images/photos/photo-12.jpg",
    "./images/photos/photo-13.jpg",
    "./images/photos/photo-14.jpg",
    "./images/photos/photo-15.jpg",
    "./images/photos/photo-16.jpg",
    "./images/photos/photo-17.jpg",
    "./images/photos/photo-18.jpg",
    "./images/photos/photo-19.jpg",
    "./images/photos/photo-20.jpg",
    "./images/photos/photo-21.jpg",
    "./images/photos/photo-22.jpg",
    "./images/photos/photo-23.jpg",
    "./images/photos/photo-24.jpg",
    "./images/photos/photo-25.jpg",
    "./images/photos/photo-26.jpg",
    "./images/photos/photo-27.jpg",
    "./images/photos/photo-28.jpg",
    "./images/photos/photo-29.jpg",
    "./images/photos/photo-30.jpg",
  ],
  heartColor: "rgb(255, 5, 5)",
  textColor: "rgba(255, 107, 156, 0.58)",
  miniHeartColor: "rgb(255, 112, 146)",
  music: "./music.mp3",
  letter: {
    greeting: "Gửi em yêu của anh,",
    lines: [
      "Giữa hàng ngàn đốm sáng lấp lánh kia, có một đốm mang tên em — sáng nhất, và luôn ở gần trái tim anh nhất.",
      "",
      "Anh không giỏi làm thơ, cũng chẳng khéo nói, nên anh gói cả bầu trời đêm nay lại, chỉ để thì thầm với em một điều thôi:",
      "",
      "Cảm ơn em đã đến, đã ở lại bên anh, và biến những ngày rất đỗi bình thường thành cả một miền thương để anh nhớ mãi.",
      "",
      "Anh yêu em — hôm nay, ngày mai, và tất cả những ngày sau nữa.",
    ],
    signature: "Mãi là của em, Anh ❤",
    hint: "Chạm vào trái tim để mở thư 💌",
    photo: "./images/photos/photo-1.jpg",
  },
  sky: { stars: true, snow: true, fireworks: true, shootingStars: true, drift: true },
};
